.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitcoinrent_qt test_bitcoinrent_qt
clean: FORCE
	$(MAKE) -C .. bitcoinrent_qt_clean test_bitcoinrent_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitcoinrent_qt_check
bitcoinrent-qt bitcoinrent-qt.exe: FORCE
	 $(MAKE) -C .. bitcoinrent_qt
